### ISSUE TITLE
Node State on the canvas doesn't change

### ISSUE THREAD

**Issue by JasperRitt** [open-decision/open-decision#101]
If you change the node with the button in the input-target-box the node-editor changes, but the former node still appears as activated on the canvas.
<img width="293" alt="Bildschirmfoto 2021-10-08 um 12 48 48" src="https://user-images.githubusercontent.com/83953718/136544047-4b3778b6-18d6-4c61-bc3e-a3f4aafbe3cf.png">

**Comment by PhilGarb** [comment]
This input should not change the active node. It changes the target of that specific input.

**Comment by JasperRitt** [comment]
It's not about the input but about the button. If you press the button, the side bar changes, but the old node keeps its active state on the canvas.

**Comment by PhilGarb** [comment]
Fixed in latest dev build.
