### ISSUE TITLE
Answers are not drag- and droppable

### ISSUE THREAD

**Issue by ghost** [open-decision/open-decision#103]
Although there is a handle to drag and drop the answers, this currently doesn't work.
![Screenshot 2021-10-11 at 11 18 51](https://user-images.githubusercontent.com/48017506/136765621-0bffd32b-abba-45b5-9a63-8bdf7fc9edf3.png)

**Comment by PhilGarb** [comment]
This has been included now. There is an open issue here -> https://github.com/framer/motion/issues/1313, about the TargetSelector not overlapping the other OptionTargetBoxes.
