### ISSUE TITLE
Canvas sometimes gets stuck

### ISSUE THREAD

**Issue by ghost** [open-decision/open-decision#107]
I don't really know how to reproduce this and I will keep this thread updated when I find out more:
It regularly happens to me that the canvas gets stuck, so I can't move it anymore. This phenomenon always occurs together with a node which is half on the canvas and can't be selected anymore. I am not sure which way the causalities work though.

**Comment by PhilGarb** [comment]
Yes please keep this updated. Preferably with screenshots if you can find the cause.
