### ISSUE TITLE
Useless canvas space

### ISSUE THREAD

**Issue by JasperRitt** [open-decision/open-decision#115]
If you close the node editor, the space that is now free seems to be dysfunctional for the nodes on the canvas. If you try, for example, to create a new node on the now free area, this will not work. If you place an already existing node there, you cannot select this node and you cannot make any connections to it.
<img width="586" alt="Bildschirmfoto 2021-10-12 um 12 41 36" src="https://user-images.githubusercontent.com/83953718/136942011-bc494b65-6c5d-4c97-abdd-8adee867a300.png">

**Comment by PhilGarb** [comment]
This is a duplicate of #92
