### ISSUE TITLE
Active state while drag and drop

### ISSUE THREAD

**Issue by JasperRitt** [open-decision/open-decision#119]
If you drag and drop a node, it is displayed in an active state. If you let go of the node, this node remains in an active state - the node should instead change to the default state.

**Comment by PhilGarb** [comment]
I cannot reproduce this. Please attach a screen recording when it happens.

**Comment by JasperRitt** [comment]
https://user-images.githubusercontent.com/83953718/137327489-bdebdaab-6dfc-4aaf-8248-ecb3007cecd2.mov
