### ISSUE TITLE
Buggy hover state in the option target box

### ISSUE THREAD

**Issue by JasperRitt** [open-decision/open-decision#123]
If you hover over the option input, the lower border of the input is blue. This shouldn't be. The option target box inputs does not need a hover state.
<img width="427" alt="Bildschirmfoto 2021-10-19 um 12 02 18" src="https://user-images.githubusercontent.com/83953718/137889752-b1a32f7a-2f67-4f71-bf0a-c538cd8a116d.png">

**Comment by PhilGarb** [comment]
I would argue that it does. The component is a combination of multiple interactive elements. These should individually still have their state styles. I would go even further and say the bug is, that the component does not have the hover style all around, like a normal input would have.

**Comment by JasperRitt** [comment]
You can of course do it that way. Either one or the other.
I don't think the hover state is particularly relevant in this case. Removing the hover state seemed like the quicker solution.
