### ISSUE TITLE
Sidebar: Content-Field: Rich Text Editor

### ISSUE THREAD

**Issue by PhilGarb** [open-decision/open-decision#17]
In order to give creators a good and extensive editing experience for the content of Nodes a rich text editor is needed.

<sup>Created from VS Code using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=issue&utm_campaign=github)</sup>

**Comment by PhilGarb** [comment]
- [x] basic formatting (bold, italics, underline, alignment)
- [x] heading levels
- [x] lists
- [x] links

### Ideas
- internal links
- word explanation
- variables (string interpolation)
- embeds (images, videos)

**Comment by ghost** [comment]
from #35 :
> * textual input field with possible text editing
> * expandable with: links, pictures, videos, documents
> * mostly contains questions

**Comment by ghost** [comment]
also from #42 

- Function: to enter diverse content, that will be displayed in the final application
- Elements: Text size, Bold, Italic, Underline, List
- Text size: Heading Large, Heading Normal, Heading Small, Text, Fussnoten
- List: Change text to a bullet List or numbered List
