### ISSUE TITLE
Allow experts to set (custom) validation for input fields

### ISSUE THREAD

**Issue by fbennets** [open-decision/open-decision#18]
We should allow experts to set validation for input fields in their apps/trees.

We should allow experts to:

- set free input fields as _required_ or _optional_
- set pre-defined basic validations (e-mail, mobile/phone, post code etc, internally we'll just use pre-defined regex expressions)
- set custom JS regex expression for fields

**Comment by PhilGarb** [comment]
Good point! I will introduce this as part of the Rich text editor. #17
