### ISSUE TITLE
Changing password does not work

### ISSUE THREAD

**Issue by fbennets** [open-decision/open-decision#194]
The spinner after confirmation (entering the current password) just spins indefinitely.

When observing the network tab, no request seems to be send after clicking the green confirmation button.

After canceling and trying to change the password again, the spinner still spins.

The password is never actually changed.

https://user-images.githubusercontent.com/35722762/177125297-9119346c-9575-4173-bca4-1ae530c6c8dd.mov

**Comment by fbennets** [comment]
The same issue occurs when trying to change the e-mail adress.

**Comment by fbennets** [comment]
And trying to delete the account

**Comment by PhilGarb** [comment]
Should be fixed by #199
