### ISSUE TITLE
highlight node tile after reopening node editor

### ISSUE THREAD

**Issue by marcus314** [open-decision/open-decision#20]
When selecting a node the node editor opens. When minimizing and reopening it, it still shows the info about the node. But the node does not get highlighted again.

**Comment by PhilGarb** [comment]
This is a result of the disconnect between the focus of a node and the state representing the node in the node editor sidebar. I think we have two options here either:
1. Discard the state of the node editor sidebar and force the user to re-select a node after closing the sidebar.
2. Highlight the currently active node differently to other nodes apart from the browsers focus.

I will investigate how the focus is moving in this pattern.

**Comment by PhilGarb** [comment]
Fixed
