### ISSUE TITLE
Canvas: Node Content

### ISSUE THREAD

**Issue by JasperRitt** [open-decision/open-decision#21]
-node name (displayed inside the node; editable inside the node as well as inside the "node-editor)
-node notes (displayed inside the node, right unser the node name; editable inside the node as well as inside the "node-editor)

**Comment by ghost** [comment]
From #42 :
**Elements:**
**Name**
Position: in the displayed node; horizontally centered; a little bit above the middle of the node
Function: changeable it in the node editor

**Input**
Position: in the middle of the upper edge of the node
Function: Input part for the connections

**Output**
Position: in the middle of the bottom edge of the node
Function: Output part for the connections

**Comment by ghost** [comment]
also just for documentation purposes:
- We discussed inline editing but discarded it for being prone to errors on such a flexible canvas
- Notes inside Nodes (😅) isn't part of the MVP, although it is an interesting idea
