### ISSUE TITLE
Canvas: click on node

### ISSUE THREAD

**Issue by JasperRitt** [open-decision/open-decision#22]
-on "name": name is editable
-on "notes": notes are editable
-on node ground: "note-editor" opens as right side-bar

**Comment by marcus314** [comment]
Wouldn't a double click be better? E.g. if I just want to move some nodes I dont want the editor to open since I need the space.

**Comment by JasperRitt** [comment]
you are totally right

**Comment by PhilGarb** [comment]
So we are talking about inline editing here? Because currently these things would only be editable from the sidebar.

**Comment by JasperRitt** [comment]
yes

**Comment by ghost** [comment]
When we discard inline editing and no**t**es for the time being (as discussed in #21 ), I can see three cases why one would click on a node:
- Open the node editor (single click)
- Drag a node (click and hold)
- Drag a connection (click on input, hold & drag)

And also those two we could consider:
- delete the node (either right click & context menu or drag into a trashcan)
- copy the node (right click & context menu)
