### ISSUE TITLE
Canvas: copy/duplication of nodes

### ISSUE THREAD

**Issue by JasperRitt** [open-decision/open-decision#23]

**Comment by marcus314** [comment]
Do wo keep the name of the parent node when copying? If we do so, if we have a list of nodes, multiple with the same name could be confusing. We could:
- Wait after testing to see if this is a problem at all
- Add a number after the name
- call the copy of "Node ABC" "Copy of Node ABC" 
- call the copy of "Node ABC" "Copy 1 of Node ABC" -> the number if the user creates multiple copys of a node

**Comment by JaRi97** [comment]
yes I think this makes sense

**Comment by JasperRitt** [comment]
I think the last two possibilities make sense

**Comment by ghost** [comment]
I like the last two proposals too. 
Copying could be done via ctrl/cmd + c & ctrl/cmd + v and through the toolbar (#24, although this could be more complicated to implement) 
@PhilGarb is this something we can include in the MVP? Would that be more of an minutes or hours (or even days) Feature?
