### ISSUE TITLE
Header Rework

### ISSUE THREAD

**Issue by JasperRitt** [open-decision/open-decision#239]
![Header](https://user-images.githubusercontent.com/83953718/181523977-00703ce3-c80d-4ff7-96ac-13b05d1024bb.png)

Elemente:
- **Home-Button**
  - goes directly to home
- **Project-Menu**
  - only for project related stuff
  - no back to home/dashboard option
  - identical to project menu in "Meine Projekte"
- **Builder/Preview-Toggle**
  - toggles only the view
  - shell stays the same
  - active node stays the same
  - horizontally centered
- **Node-Search**
  - User is not able to generate new nodes through the node-search,   when preview is active
  -  horizontally centered
- **Account-Menu**
  - only options are settings and log-out

**Comment by PhilGarb** [comment]
Die Suche mittig zu platzieren gefällt mir nicht so gut. Können wir die nicht links lassen und einfach nur den toggle in die Mitte packen?

**Comment by JasperRitt** [comment]
klar!

**Comment by JasperRitt** [comment]
![Image](https://user-images.githubusercontent.com/83953718/183399891-e15a286a-ef5c-4bb2-bebe-94cfe328963c.png)

siehe: Figma - Components-Page

**Comment by PhilGarb** [comment]
Jetzt würde ich aber den ViewSelector an der Seite orientiert zentrieren oder nicht? Das sieht ja so sehr schief aus.
