### ISSUE TITLE
Switch-Button looks like real button

### ISSUE THREAD

**Issue by ghost** [open-decision/open-decision#253]
<img width="61" alt="Bildschirmfoto 2022-08-20 um 10 07 06" src="https://user-images.githubusercontent.com/48017506/185735957-6af924d6-c480-4f83-a0f6-27491da1bd69.png">

**Comment by JasperRitt** [comment]
Toggle: 
- neutral button
- active state:
  - background-color: white;
  - box-shadow: 2;

toggle should be as wide as the other buttons

(see in figma-organisms)

<img width="272" alt="Bildschirmfoto 2022-08-23 um 14 58 59" src="https://user-images.githubusercontent.com/83953718/186164252-ad81dcf7-e227-4a8e-8183-b34e1ccf236d.png">
