### ISSUE TITLE
Dropdown selections do not need a border, especially not 2pt

### ISSUE THREAD

**Issue by JasperRitt** [open-decision/open-decision#257]
<img width="468" alt="Dropdown-Selects ohne Border" src="https://user-images.githubusercontent.com/83953718/186159514-c81500b9-787f-4afc-b8b3-d0a1490cd99b.png">

**Comment by PhilGarb** [comment]
Not sure what you mean. The element with the border is the input. This is the default focus style for all our inputs.

**Comment by JasperRitt** [comment]
I have meant the dropdown select (selective elements in the dropdown), which does not have a border on the screenshot, because i have changed it via browser inspect :) normally it has a 2pt border, but to me it should not have a border at all

**Comment by PhilGarb** [comment]
Understood. The behavior is know:

- focus by arrow key shows a focus ring
- hover does not
