### ISSUE TITLE
Canvas: Nodes

### ISSUE THREAD

**Issue by PhilGarb** [open-decision/open-decision#31]
displayed content: #21 
- node name (inline and sidebar editing)
- node notes (inline and sidebar editing)

click interactions: #22 
- on "name": name is editable
- on "notes": notes are editable
- on node background: "node-editor" opens as right side-bar

fields: #35 #36 #37

**Comment by ghost** [comment]
I will close this for now as the assumptions have changed. I think everything can be deduced from #21 & #22 now.
