### ISSUE TITLE
Canvas: Connections

### ISSUE THREAD

**Issue by JasperRitt** [open-decision/open-decision#38]
- connections between nodes
- always align themselves straight -> in other words: vertically or horizontally
- this means: if the two connected nodes are offset both vertically and horizontally, the connecting cable makes two changes in direction, each at an angle of 90 degrees
- the angles should be slightly rounded
- cables are light gray when the nodes are connected, but no condition has yet been fulfilled
- as soon as the condition has been selected through which the following node is selected, the cable appears dark
- In the middle of the cable there is a small, narrow box in which the condition is displayed
- if you click on it, the condition in the right side bar can be changed
- right-click on cable: delete option
- Validation -> not everything should be connected to everything else #30 #29

**Comment by ghost** [comment]
I wonder whether a straight/90-Degree-Connection is actually better than the currently implemented curved connection in terms of
- Connections "colliding" with / disappearing behind other nodes
- General clarity of Connections and appealing design
Don't have strong opinions on it, it's probably easy to implement & test anyways. What do you think @PhilGarb

**Comment by ghost** [comment]
Also those two we decided against (for now):
- In the middle of the cable there is a small, narrow box in which the condition is displayed
- if you click on it, the condition in the right side bar can be changed

All the other points I agree on (except maybe the alignment -> see previous post).
