### ISSUE TITLE
MVP: Builder (Master-Issue)

### ISSUE THREAD

**Issue by JasperRitt** [open-decision/open-decision#42]
### **Header** 

- [x] **Logo**

Position: in the left corner of the header, centered horizontally 

- [x] **Project Name** 

Position: to the right of OD Logo
Function: Double click on it -> Change project name 

- [x] **Preview-Mode (Switch-Button)**

Position: first Item on the right side of the top bar 
Function: Click on it -> get to Preview Mode:                                                   
Preview Mode is a separated window which appears instead of the left side bar, the right side bar and the canvas. Only the top bar stays in place. The Preview-Mode Button is a Switch-Button, which can switch between Preview- and Builder-Mode.

- [x] **Import-Button** 

Position: on the right side of the Preview-Mode-Switch-Button 
Function: Click on it -> small window appears, on on which the user can access the files on his computer and select one for import.

- [x] **Export-Button** 

Position: on the right side of the Export-Button 
Function: Click on it -> small window appears, on which the user decides, which format he wants to use for the export of the final application. 

- [x] **Help**

Position: on the right side of the Export-Button, written as „Help“ or „?“
Function: Links to Documentation; Click on it -> Documentation appears in another tab; the user has the opportunity to search the documentation through an register, as well as a search bar

 ### **Side-bar (right) / node editor**

- [x] **Node name** 

Position: at the top of the side-bar-right 
Function: click on the name-field -> edit the concrete node name 

- [x] **Text-/content-field** 

Position: right under the node name 
Function: to enter diverse content, that will be displayed in the final application 
Elements: Text size, Bold, Italic, Underline, List
Text size: Heading Large, Heading Normal, Heading Small, Text, Fussnoten
List: Change text to a bullet List or numbered List

- [x] **Input-Choices**

Position: right under the text-/content-field  
Function: create a choice of answer options for the end user (displayed as buttons)
Elements: Single Select  
Single Select: create multiple answer options by clicking a „+“-icon; the end user is able to select only one answer-option

- [x] **Conditions** 

Position: right under the Input-Choices
Function: click on it -> change the condition of the mother node in the side bar right (shown as if then statements)

If-part: the creator can add conditions and determine whether the path is to be continued if only one or all of these conditions apply
Then- part: the creator can determine where the path is taken when the conditions are met

 ### **Canvas**

- [x] **Tool-bar** 

Position: in the middle, a little above the bottom of the canvas
Function: contains tools which help to structure and edit the node-tree

**Elements:**

- [x] **Redo**

Position: first icon in the toolbar

- [x] **Undo**

Position: second icon in the toolbar

- [x] **Copy**

Position: third icon in the toolbar

- [x] **Paste**

Position: fourth icon in the toolbar

- [x] **Multi-select**

Position: fifth icon in the toolbar  
Function: Click on it -> icon is activated: the creator is able to click on the canvas and hold to multi select nodes

- [x] **Fit-map-function**

Position: sixth icon in the toolbar  
Function: click on it -> the canvas gets as big as the whole node-tree

- [x] **Canvas-background**   

Function: background for the node tree; white or light color 

- [x] **Add Node**   

Position: top left corner of the canvas
Function: displayed as a little button, looking similar to a node with a „+“-symbol in it: click, or click and drag -> create new node

- [x] **Nodes** 

**Elements:**

- [x] **Name** 

Position: in the displayed node; horizontally centered; a little bit above the middle of the node  
Function: changeable it in the node editor

- [x] **Input** 

Position: in the middle of the upper edge of the node  
Function: Input part for the connections

- [x] **Output**

Position: in the middle of the bottom edge of the node  
Function: Output part for the connections

- [x] **Connections** 

Position: between two connected nodes  
Function: link between two nodes

- [x] **Basic functions**

- [x] View examplary node-tree

- [x] Auto-saving

**Comment by ghost** [comment]
integrated into other issues; progress is being tracked via the project: mvp
