### ISSUE TITLE
Rich Text Editor editing the entire line

### ISSUE THREAD

**Issue by JasperRitt** [open-decision/open-decision#64]
you can also make changes if no text is selected, the changes will then be made for the entire line

**Comment by PhilGarb** [comment]
This is the currently intended behavior and in line with most editor implementations.

**Comment by PhilGarb** [comment]
Currently this works as intended. 
Should it behave differently? 
Which kinds of text editing does this happen with?

**Comment by JasperRitt** [comment]
[Konzept-Rich-Text-Editor.pdf](https://github.com/open-decision/Builder/files/7372311/Konzept-Rich-Text-Editor.pdf)
