### ISSUE TITLE
search bar for nodes (header)

### ISSUE THREAD

**Issue by PhilGarb** [open-decision/open-decision#68]
### Discussed in https://github.com/open-decision/Builder/discussions/50

<div type='discussions-op-text'>

<sup>Originally posted by **JaRi97** May 25, 2021</sup>
searches for suitable node content when entering characters/words (searches through node-names as well as node-notes))</div>

We are planning to add a search input that does two things. 
1. It allows the user to search for a Node by name and opens the sidebar when a Node is selected from the results.
2. It comes with a way to clear the search input and close the sidebar with it.

**Comment by ghost** [comment]
So in other words the search-bar becomes another way of navigating through the tree besides the canvas. It (always) represents what the active node is and can be changed to a different active node by deleting the text and typing (and/or selecting in the process) a new node. I like that. 
Begs the question whether a search bar could replace the Name-Field of a Node all together. In this case we would need a
- new and easy way to change a node's name and 
- convey to the user that the search field is not where the name can be changed (I don't know whether a user would actually think that or if it's just in my mental model as this is what we have done so far).

If we go through with this, I would propose to implement a Pop-Up-Window to show up whenever nodes are created which prompts the user to name the new node. This makes having to change a name a much rarer occurrence and thus diminishes the need for an in-your-face type of fuction to change a name as the current node name field is.

Here is an image of the current search bar (upper) and name field (lower). I am proposing to get rid of the name field.
![Screenshot 2021-09-13 at 18 21 45](https://user-images.githubusercontent.com/48017506/133120940-fc391f27-7805-40ea-8405-6101d0063c37.png)

What do you think? @JaRi97 @PhilGarb

**Comment by JasperRitt** [comment]
Bringing both together is actually how i understood Philipp originally. To me having a prompt pop-up is no proper solution. I would suggest to do a dropdown function for the search bar. So that you have a search bar and a change node name bar at once. Then you could (as i still like it) have in addition a double-click function for the node names on the canvas nodes.

**Comment by JasperRitt** [comment]
an alternative to a dropdown could be a toggle, so that you can recognize both functions better.

**Comment by JasperRitt** [comment]
I've thought some more about it and now I have some pretty strong arguments against combining the two elements. We should talk about it next week and i tell you my pros and cons.

**Comment by PhilGarb** [comment]
We have decided to revisit the decision on whether to combine the two inputs at a later time. For the moment we will keep them as two separate inputs. The functionality is now included.

**Comment by JasperRitt** [comment]
I think I have now understood Aaron as far as the search bar is concerned. I now go along with the analysis that two input fields with the same name are confusing. The miscommunication came from thinking of the search bar as a search bar that is specifically only there for search input. In the current Dev, however, it is equivalent to the current node selection, i.e. if you select a node on the canvas, the node is also selected in the search bar. If you don't enter anything of your own in the search bar, however, I would leave it blank. As described: a search bar that is only there for your own entries. This also prevents the problem with the two input fields with the same input, where you always have to think about which of the two does what.

However, if we want to keep that with the equivalence of grade selection and search bar entry, I am also in favor of a toggle. Then the search bar is not a search bar, but a node selection.

**Comment by PhilGarb** [comment]
I think it is important to not break the connection between what the selected node is. Showing it in the search input only sometimes and not everytime is more confusing in my opinion. 

Showing the name twice is unnecessary duplication, but not the worst in the world. I would either go for a toggle to update the name in the search bar or replace the name input with a heading. That could frame the sidebar a little nicer and include a button to edit the name. I see the main issue in having two identically looking inputs showing the same information.

**Comment by ghost** [comment]
@JaRi97 yes that is the way I imagined it, however I do not advise to combine the two fields, but rather get rid of the name-input altogether (and create another way of changing the name, see my first answer in this thread). I'm mostly with Phil in terms of breaking the connection being confusing.

I think we have to ways to go from here if we gather our findings:

**We treat the search bar as a mere search bar as you envision it @JaRi97.**

In this case there is no reason to keep the search bar at the top of the node editor, in contrary it may lead to confusion as @PhilGarb elaborates. So we have to find a better place for it, maybe somewhere on the canvas. This also means that the node-name-input-field remains the undisputed hero of the node editor, displaying the name, proud as always.

**We treat the search bar as a "node selector" (as you call is @JaRi97 and as @PhilGarb and me are proposing).**

In this case we get another sleek way to navigate through the tree, which might even be quite keyboard-friendly as it can be easily accessed from the node editor (just by pressing "up" a couple times). I really like this alternative way of changing nodes and think I myself would often use this option, as I am quite lazy with the mouse sometimes. When we do this, the "node selector" (or search bar) always contains the name of the active node, irrespective of how it was activated (canvas or node selector). I have already elaborated on that in my first answer on this thread. The challenge of this approach is, that the node-name-input-field now has a contender for the title "hero of the node editor" (as you can see in the current implementation), which we all think is confusing. So what we have to do when we follow this approach, is find another way to edit a node name. We could to this via the toggle @JaRi97 proposed (Screenshot below), but I agree with you @JaRi97 that this kind of breaks the mental model. I would expect to be able to change the node in three ways, which we can talk about:

1. As a promt when creating a node
2. As an option when right-clicking on a node on a canvas
3. somewhere IN, but not above the node-editor, iE through a small button [change node name]

I think all three options could be implemented (simultaneously), but we could talk whether the first might be too disrupting.

When talking about the two approaches (search bar vs. node selector) I am quite in love with the idea of the node selector, I would however also be fine with the more conservative search bar if you two prefer it.

Screenshot of the Toggle:

![Screenshot 2021-09-28 at 21 01 10](https://user-images.githubusercontent.com/48017506/135149410-c07e109e-5cda-4273-bbf6-d4f4dd236066.png)
