### ISSUE TITLE
Inputs and outputs of the nodes

### ISSUE THREAD

**Issue by JasperRitt** [open-decision/open-decision#94]
The inputs and outputs of the nodes are not centered vertically on the node-edges.
<img width="332" alt="Bildschirmfoto 2021-10-05 um 15 12 40" src="https://user-images.githubusercontent.com/83953718/136029883-31c46ef2-40ee-4cda-b53a-0e1b3e61fb58.png">

**Comment by PhilGarb** [comment]
Has been fixed
