### ISSUE TITLE
Active States of Inline-Inputs

### ISSUE THREAD

**Issue by JasperRitt** [open-decision/open-decision#97]
Inline inputs with an icon should only show it's state by the icon. Otherwise the border collides with the button.

<img width="186" alt="Bildschirmfoto 2021-10-08 um 12 16 15" src="https://user-images.githubusercontent.com/83953718/136540491-14b33f97-c179-451f-be6a-1a605687f59a.png">
<img width="334" alt="Bildschirmfoto 2021-10-08 um 12 16 06" src="https://user-images.githubusercontent.com/83953718/136540555-52770d12-64e8-4652-b0fc-f05c95eb84ce.png">

**Comment by ghost** [comment]
All elements must be selectable in some way through this kind of border for keyboard use and accessibility. So I would advise against removing the border.

Another visual bug I am adding here as it concerns the same matter: The icon next to the node name input in the sidebar confuses me. It kind of acts like a button (it turns blue on hover) but i cannot click on it (or nothing happens). This is deeply unsatisfying for me as a user.
Two fixes I have in mind:
1. When you click on the icon, your focus changes to the now active input and you can start typing, or
2. remove the icon and add a small icon or "edit"-text behind the node name (as shown in this very professional draft:)
![Screenshot 2021-10-11 at 11 02 31](https://user-images.githubusercontent.com/48017506/136764740-a1e4e659-ca88-4a54-b6eb-36a8f0183714.png)
)

**Comment by PhilGarb** [comment]
@JaRi97 does this happen when selecting it with the mouse or when using the tab key?
@aaronrothmann I agree this is not perfect. Currently the icon is just an indicator and not interactable. What would you preferred solution?
I think making the indicator into an actual button that focuses the input, but keeps the current states to indicate interaction with the input would be my preferred solution.

**Comment by JasperRitt** [comment]
To your first question: It happens when selecting with the mouse. 
As far as the icon is concerned, I find the solution to be the best to turn the icon into a button.

**Comment by ghost** [comment]
Then let's go with the button-solution
