### ISSUE TITLE
Active States of Inputs

### ISSUE THREAD

**Issue by JasperRitt** [open-decision/open-decision#99]
Active states of inputs sometimes don't behave right, because they use the wrong box for the blue stroke.
<img width="500" alt="Bildschirmfoto 2021-10-08 um 12 14 47" src="https://user-images.githubusercontent.com/83953718/136541230-f5429733-a725-4550-af8f-111d92c34aaa.png">
<img width="451" alt="Bildschirmfoto 2021-10-08 um 12 15 04" src="https://user-images.githubusercontent.com/83953718/136541245-703db684-b1e3-4b17-afd7-991e2ce98569.png">

**Comment by PhilGarb** [comment]
Which browser are you using?

**Comment by JasperRitt** [comment]
Firefox

**Comment by PhilGarb** [comment]
Has been fixed.
